[package]
name = "gm_cron"
authors = ["Earu"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gmod = { version = "*", default-features = false, features = ["gmcl"] }
job_scheduler = "1.2.1"
closure = "0.3.0"